function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "temperatureSensor"};
	this.sidHashMap["temperatureSensor"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "temperatureSensor:7"};
	this.sidHashMap["temperatureSensor:7"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "temperatureSensor:13"};
	this.sidHashMap["temperatureSensor:13"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/Analog Input"] = {sid: "temperatureSensor:1"};
	this.sidHashMap["temperatureSensor:1"] = {rtwname: "<Root>/Analog Input"};
	this.rtwnameHashMap["<Root>/Compare To Constant"] = {sid: "temperatureSensor:7"};
	this.sidHashMap["temperatureSensor:7"] = {rtwname: "<Root>/Compare To Constant"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "temperatureSensor:4"};
	this.sidHashMap["temperatureSensor:4"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Digital Output"] = {sid: "temperatureSensor:13"};
	this.sidHashMap["temperatureSensor:13"] = {rtwname: "<Root>/Digital Output"};
	this.rtwnameHashMap["<Root>/Divide"] = {sid: "temperatureSensor:5"};
	this.sidHashMap["temperatureSensor:5"] = {rtwname: "<Root>/Divide"};
	this.rtwnameHashMap["<Root>/Gain"] = {sid: "temperatureSensor:2"};
	this.sidHashMap["temperatureSensor:2"] = {rtwname: "<Root>/Gain"};
	this.rtwnameHashMap["<Root>/Gain1"] = {sid: "temperatureSensor:6"};
	this.sidHashMap["temperatureSensor:6"] = {rtwname: "<Root>/Gain1"};
	this.rtwnameHashMap["<Root>/Gain2"] = {sid: "temperatureSensor:10"};
	this.sidHashMap["temperatureSensor:10"] = {rtwname: "<Root>/Gain2"};
	this.rtwnameHashMap["<Root>/NOT"] = {sid: "temperatureSensor:11"};
	this.sidHashMap["temperatureSensor:11"] = {rtwname: "<Root>/NOT"};
	this.rtwnameHashMap["<Root>/PWM"] = {sid: "temperatureSensor:12"};
	this.sidHashMap["temperatureSensor:12"] = {rtwname: "<Root>/PWM"};
	this.rtwnameHashMap["<S1>/u"] = {sid: "temperatureSensor:7:1"};
	this.sidHashMap["temperatureSensor:7:1"] = {rtwname: "<S1>/u"};
	this.rtwnameHashMap["<S1>/Compare"] = {sid: "temperatureSensor:7:2"};
	this.sidHashMap["temperatureSensor:7:2"] = {rtwname: "<S1>/Compare"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "temperatureSensor:7:3"};
	this.sidHashMap["temperatureSensor:7:3"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/y"] = {sid: "temperatureSensor:7:4"};
	this.sidHashMap["temperatureSensor:7:4"] = {rtwname: "<S1>/y"};
	this.rtwnameHashMap["<S2>/In1"] = {sid: "temperatureSensor:13:7"};
	this.sidHashMap["temperatureSensor:13:7"] = {rtwname: "<S2>/In1"};
	this.rtwnameHashMap["<S2>/Data Type Conversion"] = {sid: "temperatureSensor:13:11"};
	this.sidHashMap["temperatureSensor:13:11"] = {rtwname: "<S2>/Data Type Conversion"};
	this.rtwnameHashMap["<S2>/Digital Output"] = {sid: "temperatureSensor:13:12"};
	this.sidHashMap["temperatureSensor:13:12"] = {rtwname: "<S2>/Digital Output"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
